In [7]:
import json
import pickle
import os
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
from torch.distributions.normal import Normal
import torch

In [10]:
torch.ones(9, 4).div(torch.tensor([1, 2, 1, 2]))

tensor([[1.0000, 0.5000, 1.0000, 0.5000],
        [1.0000, 0.5000, 1.0000, 0.5000],
        [1.0000, 0.5000, 1.0000, 0.5000],
        [1.0000, 0.5000, 1.0000, 0.5000],
        [1.0000, 0.5000, 1.0000, 0.5000],
        [1.0000, 0.5000, 1.0000, 0.5000],
        [1.0000, 0.5000, 1.0000, 0.5000],
        [1.0000, 0.5000, 1.0000, 0.5000],
        [1.0000, 0.5000, 1.0000, 0.5000]])

In [16]:
x = torch.isinf(torch.tensor([1, float('inf'), 2, float('-inf'), float('nan')]))
if True in x:
    print(x)
y = torch.isinf(torch.tensor([1,  2, float('nan')]))
if True in y:
    print(y)

tensor([False,  True, False,  True, False])


In [2]:
with open('../../data/coco/annotations/instances_train2017.json', 'r') as jsonfile:
    train_annotations = json.load(jsonfile)

In [11]:
train_annotations.keys()

dict_keys(['info', 'licenses', 'images', 'annotations', 'categories'])

In [20]:
len(train_annotations['annotations'])/float(len(train_annotations['images']))

7.27046082832433

In [21]:
len(train_annotations['images'])

118287

In [18]:
annotation_df = pd.DataFrame.from_dict(train_annotations['annotations'])

In [25]:
annotation_df.groupby("category_id")

segmentation    area  iscrowd  image_id    bbox      id
category_id                                                         
1                  262465  262465   262465    262465  262465  262465
2                    7113    7113     7113      7113    7113    7113
3                   43867   43867    43867     43867   43867   43867
4                    8725    8725     8725      8725    8725    8725
5                    5135    5135     5135      5135    5135    5135
...                   ...     ...      ...       ...     ...     ...
86                   6613    6613     6613      6613    6613    6613
87                   1481    1481     1481      1481    1481    1481
88                   4793    4793     4793      4793    4793    4793
89                    198     198      198       198     198     198
90                   1954    1954     1954      1954    1954    1954

[80 rows x 6 columns]

In [22]:
with open('../../data/coco/annotations/instances_val2017.json', 'r') as jsonfile:
    val_annotations = json.load(jsonfile)

In [23]:
len(val_annotations['images'])

5000

In [24]:
len(val_annotations['annotations'])

36781

In [6]:
d = Normal(loc=torch.tensor([0., 0.]), scale=torch.tensor([0.5, 0.5]))
d.log_prob(torch.tensor([[0., 0.], [0.1, 0.2]])).exp

tensor([[-0.2258, -0.2258],
        [-0.2458, -0.3058]])